import pandas as pd
s=pd.DataFrame({"names": ["Ali", "Sara", "Ahmed"], "age":[20, 21, 19]})
print(s)
print(s.dtypes)
print(s.head())
print(s.tail(3))
print(s.shape)
print(s.columns)
print(s.info())
print(s.describe())
print(s[["age","names"]])
print(s.loc[1])
print(s.iloc[[1]])
print(s[s["age"] >20])
print(s[s["names"] =="Ali"])